### ISSUE TITLE
[Request] Add compatibility for this plugin? (MariaDB)

### ISSUE THREAD

**Issue by kmichailg** [staudenmeir/laravel-migration-views#1]
https://github.com/ybr-nx/laravel-mariadb

Not currently reading `mariadb` as a supported database.

**Comment by staudenmeir** [comment]
What Laravel version are you using?

**Comment by kmichailg** [comment]
Currently using `Laravel Framework 5.8.31` tested also on `Laravel Framework 5.8.33`.

**Comment by staudenmeir** [comment]
Laravel 5.8 does support JSON queries on MariaDB natively.

**Comment by kmichailg** [comment]
https://laravel.com/docs/5.8/queries#json-where-clauses

Not listed here, I've encountered problems with a prior version 5.6/5.7 but I haven't tested with 5.8 using `mysql` driver. Not sure if issue persists. I don't see why we can't accommodate this change though? It's a one-line change and doesn't affect any other parts of the code.

**Comment by staudenmeir** [comment]
Please test that first.
