### ISSUE TITLE
QUERY PARAMETER CLOSURE

### ISSUE THREAD

**Issue by knighht** [staudenmeir/laravel-migration-views#4]
Hi staundenmeir, 

I think it is a better idea if you implemented the `$query` parameter with `Closure` or `Callable` instead of `Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|string`. It's not just make the code looks tidier, it also make the code readeable especially to new programmer like me :P.

Regards,
knighht

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by staudenmeir** [comment]
I decided against it: For such a minor feature, it would require too much new code.
