### ISSUE TITLE
[QUESTION] Does it support materialized view?

### ISSUE THREAD

**Issue by skyfall174** [staudenmeir/laravel-migration-views#6]
Hello, i just looking for lib that can create view and also materialized view.

**Comment by staudenmeir** [comment]
Not yet, but I'll look into it.

**Comment by staudenmeir** [comment]
What database and Laravel version are you using?

**Comment by staudenmeir** [comment]
The package now supports materialized views:
https://github.com/staudenmeir/laravel-migration-views?tab=readme-ov-file#materialized-views
