### ISSUE TITLE
Drop view problem

### ISSUE THREAD

**Issue by Djenkaa** [staudenmeir/laravel-migration-views#7]
I have problem with dropping view 
It tells me that the view already exists when I run php artisan migrate:fresh

**Comment by staudenmeir** [comment]
What does your migration look like?

**Comment by Djenkaa** [comment]
Like this

`
use Staudenmeir\LaravelMigrationViews\Facades\Schema;


public function up(){

$sql = "my sql query";

Schema::createView('view-name', $sql);
}

public function down(){

Schema::dropViewIfExists('view-name');
}
`

**Comment by staudenmeir** [comment]
`migrate:fresh` doesn't drop views by default, you need to add `--drop-views`.

**Comment by Djenkaa** [comment]
> `migrate:fresh` doesn't drop views by default, you need to add `--drop-views`.

Thanks!
