### ISSUE TITLE
A seperate new "migrate:fresh" that drop the views too?

### ISSUE THREAD

**Issue by ziming** [staudenmeir/laravel-migration-views#8]
Currently as long as 1 view migration exist

php artisan migrate:fresh will no longer work because it will throw a view already exist command

So suggestion to add 1 new command to this package that drop all tables and views

**Comment by staudenmeir** [comment]
Did you see this line in the README?

> If you are using php artisan migrate:fresh, you can drop all views with --drop-views (Laravel 5.6.26+).

**Comment by ziming** [comment]
Ah okay, I missed it. Thank you!
