### ISSUE TITLE
Update a view with multiple tables

### ISSUE THREAD

**Issue by bilogic** [staudenmeir/laravel-migration-views#9]
Hi,

Looking at your extensive list of DB related packages. I wonder if you ever had to create a DB VIEW consisting of multiple tables and still be able to INSERT/UPDATE to the VIEW using Eloquent.

The use case is like `trait` in PHP which can be added to a class to enhance its behavior. Likewise, I'm attempting to enhance an existing table by combining it with another using a VIEW, but the resulting code in Laravel hasn't been good enough.

**Comment by staudenmeir** [comment]
Hi @bilogic,
Can you share the relevant parts of your code? What does the view look like?

**Comment by bilogic** [comment]
Hi @staudenmeir 

Thanks for getting back.

```PHP
$sql = <<<SQL
    CREATE OR REPLACE VIEW {$this->tableWithTrait} AS
    SELECT
        {$fields}
    FROM `{$this->table}`
    INNER JOIN `{$this->traitTable}` ON `{$this->table}`.`id` = `{$this->traitTable}`.`{$this->tablePointer}`
SQL;
```

Above is my SQL, where `$fields` consist of all fields from `>table` and all fields from `>traitTable`, only excluding `>traitTable.id`, i.e. when you see `id` in the `>tableWithTrait`, it is the `id` of `>table`

No issues with reading, but I got really stuck when trying to create/update/save given the constraints of 

1. MySQL https://dev.mysql.com/doc/refman/8.0/en/view-updatability.html, only updates to 1 table at a time
2. The numerous methods that need to be overridden in Laravel's Eloquent (https://github.com/michaelachrisco/ReadOnlyTraitLaravel/blob/main/src/ReadOnlyTrait.php)

I have basically given up this idea, unless something wonderful comes out of our conversation. Thank you.

**Comment by bilogic** [comment]
Another issue I faced with VIEWS here https://github.com/laravel/framework/discussions/48991

**Comment by staudenmeir** [comment]
> No issues with reading, but I got really stuck when trying to create/update/save given the constraints of
> MySQL https://dev.mysql.com/doc/refman/8.0/en/view-updatability.html, only updates to 1 table at a time

Would you need to update both tables?

Can you share a high-level overview of an actual use case? What are examples of `$table` and `$traitTable`?

**Comment by bilogic** [comment]
Perhaps it is easier to start with what I see as a problem:

1. There are many types of contacts, e.g. `users`, `customers`, `buyers` `students` etc
2. They have common fields such as names, email etc
3. Some may have additional specific fields
4. I ran into the problem where there are inconsistencies in the common fields, e.g. I did not add `email` to `buyers` and now there is a request for it
5. What would be great is there is a single place to modify these common fields and it will cascade across all associated tables
6. At the same time, I'm able to access `buyers` through 1 eloquent model, abstracted away from these table details

Make sense?

**Comment by staudenmeir** [comment]
What does your view look like in this case?

**Comment by bilogic** [comment]
1. I used `$table` for common fields and `$traitTable` for specific fields
2. However, both have `id` and my view will expose the one from `$table` because it is unique across the whole DB
3. `$table` has `trait_table_id` to join the 2 tables, this field is not exposed in the view

**Comment by staudenmeir** [comment]
> There are many types of contacts, e.g. users, customers, buyers students etc
> I used $table for common fields and $traitTable for specific fields

Do you have one shared table for the common fields and one for each contact type and its specific fields?
And Eloquent models for all contact types?

**Comment by bilogic** [comment]
> Do you have one shared table for the common fields and one for each contact type and its specific fields? 

Correct

> And Eloquent models for all contact types?

Yes

**Comment by staudenmeir** [comment]
I don't see a way to make that work with views.

**Comment by bilogic** [comment]
Thanks, I pretty much came to the same conclusion, but somehow feel that I'm still missing something and that this is a solvable problem. (Perhaps just not with VIEWs alone)

**Comment by staudenmeir** [comment]
The only solution I see for inserting and updating would be to execute two separate queries each time (when updating, that would depend on the affected columns). You can also update both tables in a single query, but that's probably more complicated to implement.
